version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: learning-roadmap-app
    container_name: learning-roadmap-app
    restart: unless-stopped
    ports:
      - "3010:3000"
    env_file: .env
    # environment:
    #   - DATABASE_URL=${DATABASE_URL} 
    #   - NODE_ENV=production
    volumes:
      - ./public/uploads:/app/public/uploads
    # networks:
    #   - roadmap-net

    # networks:
    #   roadmap-net:
    #     driver: bridge
